# Generated by Django 6.0.3 on 2026-03-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('saving_deposit', 'Saving Deposit'), ('saving_withdrawal', 'Saving Withdrawal')], max_length=20),
        ),
    ]
