# Generated by Django 6.0.3 on 2026-03-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_alter_savingssnapshot_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingssnapshot',
            name='budget',
        ),
    ]
