# Generated by Django 6.0.3 on 2026-03-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='type',
        ),
    ]
