# Generated by Django 6.0.3 on 2026-03-17 13:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetplan',
            name='planned_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
